FROM apache/airflow:2.9.3-python3.11 
USER root WORKDIR /opt/airflow 
COPY requirements.lock.txt /opt/airflow/requirements.lock.txt 
RUN pip install --no-cache-dir -r /opt/airflow/requirements.lock.txt # add this COPY pyproject.toml /opt/airflow/pyproject.toml 

COPY airflow/dags /opt/airflow/dags 
COPY src /opt/airflow/src 
RUN pip install --no-cache-dir . 
# ENV PYTHONPATH=/opt/airflow 

USER airflow